### ISSUE TITLE
Script fail when trying to download Torec subs

### ISSUE THREAD

**Issue by guynimni382** [slmosl/service.subtitles.torec#4]
Hi dear friend,

Since I'm new to this I hope you can bear with me :-)

I get a script error when trying to download subtitles from Torec using your addon.
It doesn't happen for other subtitle sources (Subcenter, subtitle.co.il... etc.)

Downloading directly from the website works fine.

I'm not sure where the log files reside so I didn't attach any log files.

Did you come across any issues like mine lately ?

**Comment by slmosl** [comment]
All the afore-mentioned issues should be fixed in the 1.0.3 version, I've created a pre-release version you can use by installing this zip file - https://github.com/slmosl/service.subtitles.torec/archive/1.0.3.zip

Please, let me know if you're having any issues.

**Comment by ghost73** [comment]
yes its works fine now.
thanks
please close the case

**Comment by itzik-gabay** [comment]
Script fail when trying to download Torec subs
Although I downloaded the latest version 1.0.3
