### ISSUE TITLE
Fail to download subtitle | TOO MANY DL

### ISSUE THREAD

**Issue by myakove** [slmosl/service.subtitles.torec#8]
I'm using your scripts to download subtitles from Torec and I get error TOO MANY DL
I think Torec has change the timewaited.
I changed it to 20 in:
getDownloadLink()
params = {"sub_id" : subID, "code": optionID, "sh" : "yes", "guest" : requestID, "timewaited" : "16"}
And now it works.

Just FYI

**Comment by morsela** [comment]
Thanks for the tip, @myakove.
I'll add this important fix to the soon to be uploaded version (1.0.3)

**Comment by slmosl** [comment]
Thanks for the tip, @myakove.
I'll add this important fix to the soon to be uploaded version (1.0.3)

**Comment by myakove** [comment]
np, Also I notice that some subs are not names like the zip file and the script miss it in savedata()
You can make all matches using the SRT file from the zip:
zip_dir_path = os.path.dirname(file_name)
zip = zipfile.ZipFile(file_name)
files_in_zip = zip.filelist
for zf in files_in_zip:
    if zf.filename.endswith('.srt'):
        orig_srt_file = zf.filename

and compare it:
if srt_file.endswith(".srt") and srt_file == orig_srt_file:
